#! /bin/sh

# Polkit authentication for giving privileges to applications
lxsession &

# Keep clipboard contents safe
parcellite -daemon &

# Compositing, transparency, shadows
compton &

# cursor theme
xsetroot -cursor_name left_ptr

# Monitors
if [ "$(bspc query -M | wc -l)" == 3 ]
then
    mtriple
else
    msingle
fi

# Don't switch off monitors completely
# Needed because Displayport-using monitors never come back on again
xset -dpms &

# Keyboard shortcuts
sxhkd &

# BSPWM options
bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color \#343d46
bspc config active_border_color \#343d46
bspc config focused_border_color \#65737e
bspc config presel_feedback_color \#65737e

bspc config click_to_focus any
bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# RULES

# AUTOSTART
